version: '3.6'
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - app/config/.dev.env
    depends_on:
      - redis

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: clients_database

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    depends_on:
     - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    ports:
      - '80:80'
