version: '3.6'
services:
  flask:
    build: ./service
    ports:
      - "5000:5000"
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: clients_database
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
