version: '3.6'
services:
  flask:
    build: .
    expose:
      - "5000"
    env_file:
      - app/config/.dev.env
    depends_on:
      - redis
    entrypoint: ["/auth/app/entry.sh"]
    volumes:
      - static:/auth/app/static/

  postgres:
    image: postgres:13
    ports:
      - "5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: clients_database

  redis:
    image: "redis:alpine"
    hostname: redis
    expose:
      - "6379"
    depends_on:
     - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/var/html/static/
    depends_on:
      - flask
    ports:
      - '80:80'

volumes:
  postgres_data:
  static: