BAD_REQUEST = {"message": "bad request"}
ROLE_EXISTS = {"message": "role already exists"}
ROLE_CREATE = {"message": "role created"}
DEFAULT_ROLE_NOT_DELETE = {"message": "default roles cannot be deleted"}
ROLE_DELETE = {"message": "role removed"}
ROLE_NOT_EXIST = {"message": "the role does not exist"}
ROLE_CHANGE = {"message": "role change"}
SHORT_PASSWORD = {"message": "password too short"}
WRONG_EMAIL = {"message": "The email address is not valid"}
WRONG_LOGIN = {"message": "login too short or not exist"}
REGISTRATION_COMPLETE = {"message": "registration complete"}
REGISTRATION_FAILED = {"message": "login or email already registered"}
